import { Space_Grotesk } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./content/css/styles.min.css";
import Head from "next/head";
const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Maven",
  description: "Generated by codewave",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
